### ISSUE TITLE
Finalize browser extension for FF 52+.

### ISSUE THREAD

**Issue by foxik** [ufal/korektor#24]
The web extension plugin generally seem to work in FF 52+. Things left to sort out:
- [ ] Should we add minimum required FF version? If I understand correctly, that requires "applications" key in the manifest, and Chrome doesn't know it and prints a warning. Maybe we need two manifests?
- [ ] Also do we need to include the extension id?
- [ ] Check that the onStartup and onInstalled works correctly in FF 52 (it does not with Temporary Add-on).
- [ ] Publish the version on AMO.

@MikkCZ (please feel free to edit this)

**Comment by MikkCZ** [comment]
To the applications key in manifest, Chrome shows a warning when loading the extension as a developer, but that should not be visible to the users. The same way Firefox shows warnings about background.persistent and minimum_chrome_version. As the extension ID you can (and probably should) use `korektor_spellchecker@ufal.mff.cuni.cz` from the removed install.rdf.

**Comment by MikkCZ** [comment]
When uploading the extension to AMO, I would suggest to add screenshots of the context menu and some textual information into description, how to use the addon. As it works in Czech only at this moment, it would be nice if it's in Czech. ;)
