### ISSUE TITLE
Port the browser add-on to work in Firefox for Android

### ISSUE THREAD

**Issue by MikkCZ** [ufal/korektor#30]
I would like to make the add-on work in Firefox for Android. Probably there won't be many changes in the logic needed, but the UI will need a refresh. It's also a good opportunity to replace jQuery with new JavaScript features, and possibly remove jQuery entirely to make the add-on lighter.

**Comment by MikkCZ** [comment]
The development seems stopped anyway. Also this issue was more like a reminder for myself, what I would like to do. However as this is more a matter of personal opinion, and I am not contributing to the project anymore, closing (as won't fix).

**Comment by foxik** [comment]
BTW, we are developing a substantially better version of Korektor (which is able to perform also grammar correction), which is able to work for nearly any language (see https://arxiv.org/pdf/1910.00353.pdf for our latest paper) -- that is why the development stopped in this repository. But we hope to have the new version running in a ~year on LINDAT.
